export enum ProductPattern {
  CHECK_PRODUCT_EXISTS = 'CHECK_PRODUCT_EXISTS',
  CHECK_PRODUCT_BY_ID = 'CHECK_PRODUCT_BY_ID',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
}
